alias c='wl-copy'
alias cls=clear
alias cp='cp -i'
alias dl='wl-paste | xargs curl -L'
alias lg='lazygit'
alias mv='mv -i'
alias q=exit
alias v='wl-paste'
alias vim="lvim"
alias svim="sudo $HOME/.local/bin/lvim"
alias apt="apt-fast"
alias tmp="mkdir -p /tmp/raghav/ && cd /tmp/raghav/"
